version: '3.8'

services:
  mysql-master:
    image: mariadb:11.4
    container_name: mysql-master
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_MASTER_PORT}:3306"
    volumes:
      - ./mysql-master/data:/var/lib/mysql
      - ./mysql-master/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./backups:/backups
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mysql-slave:
    image: mariadb:11.4
    container_name: mysql-slave
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_REPLICATOR_USER}
      MYSQL_PASSWORD: ${MYSQL_REPLICATOR_PASSWORD}
    ports:
      - "${MYSQL_SLAVE_PORT}:3306"
    volumes:
      - ./mysql-slave/data:/var/lib/mysql
      - ./mysql-slave/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - mysql_network
    depends_on:
      - mysql-master
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-master
      PMA_PORT: 3306
    networks:
      - mysql_network
    depends_on:
      - mysql-master
    restart: unless-stopped

  prod_php:
    container_name: prod_php
    build: ./application/projects/prod/app/docker/php/
    volumes:
      - ./application/projects/prod/app/:/var/www/html:delegated
      - ./application/projects/prod/api:/var/www/html/backend:delegated
    restart: always
    networks:
      - mysql_network

#  staging_php:
#    container_name: staging_php
#    build: ./application/projects/staging/app/docker/php/
#    volumes:
#      - ./application/projects/staging/app/:/var/www/html:delegated
#      - ./application/projects/staging/api:/var/www/html/backend:delegated
#    restart: always
#    networks:
#      - mysql_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./application/projects/prod/app/:/var/www/html:delegated
      - ./application/projects/prod/api:/var/www/html/backend:delegated
      - ./application/projects/staging/app/:/var/www/html:delegated
      - ./application/projects/staging/api:/var/www/html/backend:delegated
    networks:
      - mysql_network
    depends_on:
      - prod_php
#      - staging_php
      - phpmyadmin

networks:
  mysql_network:
    driver: bridge