version: '3.8'

services:
  mysql-master:
    image: mariadb:11.4
    container_name: mysql-master
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_MASTER_PORT}:3306"
    volumes:
      - ./mysql-master/data:/var/lib/mysql
      - ./mysql-master/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./backups:/backups
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mysql-slave:
    image: mariadb:11.4
    container_name: mysql-slave
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_REPLICATOR_USER}
      MYSQL_PASSWORD: ${MYSQL_REPLICATOR_PASSWORD}
    ports:
      - "${MYSQL_SLAVE_PORT}:3306"
    volumes:
      - ./mysql-slave/data:/var/lib/mysql
      - ./mysql-slave/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    networks:
      - mysql_network
    depends_on:
      - mysql-master
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-master
      PMA_PORT: 3306
    ports:
      - "${PHPMYADMIN_PORT}:80"
    networks:
      - mysql_network
    depends_on:
      - mysql-master
    restart: unless-stopped
#  nginx:
 #   image: nginx:latest
  #  container_name: nginx
   # ports:
    #  - "80:80"
   # volumes:
    #  - ./nginx/conf.d:/etc/nginx/conf.d:ro
   # networks:
    #  - mysql_network
   # depends_on:
    #  - phpmyadmin

networks:
  mysql_network:
    driver: bridge
